### ISSUE TITLE
Is a more complex REST uri possible?

### ISSUE THREAD

**Issue by nederhrj** [elasticsales/flask-mongorest#50]
I am trying to implement flask-mongorest in my project. So far, it works really nice. Thanks for the hard work on this project.

Now, I would like to build more complex Rest uri's like 

/user/(int: user_id)/article/(int: article_id)/(read)

Where for user (int: user_id) I can tag article (int: article_id) as read.

The example code only gives examples like /user/(int: user_id). Is the uri I am trying to build possible? Could you give me some hints how to implement this?

Thanks!

**Comment by thomasst** [comment]
We don't support this format currently, sorry about that. It would require changes in several parts of the module (`MongoRest.register` and views).
