### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by Marigold** [elasticsales/flask-mongorest#58]
I would like to add custom validation to some fields of the document (and optionally return error), but I don't know what methods should I override (Resource.create_object or ResourceView.post?). It's not just validation, I'm looking for a way how to run custom code in POST requests. Is this even possible? Thanks!

**Comment by thomasst** [comment]
We support validation schemas using cleancat (https://github.com/elasticsales/cleancat). If this isn't flexible enough you can also override `save_object` in the resource and  `post` in the view.  Check out the latest `cleanup` branch: https://github.com/elasticsales/flask-mongorest/pull/62
