### ISSUE TITLE
Ability to apply a default filter to Document

### ISSUE THREAD

**Issue by mgmonteleone** [elasticsales/flask-mongorest#63]
In our use case we would like to filter out documents from a defined resource (do not return documents that have been logically deleted).

How would this be done with mongorest? Using a signal perhaps?

**Comment by wojcikstefan** [comment]
Hey @mgmonteleone, you can override the resource's `get_queryset` like this:

```
def get_queryset(self, *args, **kwargs):
    return super(YourResource, self).get_queryset(*args, **kwargs).filter(is_deleted=False)
```

**Comment by mgmonteleone** [comment]
:) Thanks for the response!

I also was able to do it by doing a query_manager decorator:

    @queryset_manager
    def objects(selfdoc_cls,queryset):
        return queryset.filter(deleted__ne=True) 

Any drawbacks to that?
